version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: your_username
      DB_PASSWORD: your_password
      DB_NAME: your_db
      DB_PORT: 5432